### ISSUE TITLE
Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by BenjaminSemah** [BertrandConxy/To-do-list-app#4]
Hello  @BertrandConxy

Your project looks professional.
- ReadMe is well written.
- UI/UX of the project offers a user friendly experience
- Code is clean and easy to understand.

Keep it up and best wishes.

**Comment by aeon9300** [comment]
Your code looks good, and it is functioning appropriately. Great work!

**Comment by BertrandConxy** [comment]
Thank you @BenjaminSemah  and @aeon9300. I appreciate your reviews.
